### ISSUE TITLE
Custom Avatars not working

### ISSUE THREAD

**Issue by MarkKevin08** [WPUserManager/wp-user-manager#380] opened 2023-06-07 09:05 UTC
## Current Outcome

Currently, the option Custom Avatars that lets users set their own profile picture is not working due to the attribute srcset in the html element (img):
![image](https://github.com/WPUserManager/wp-user-manager/assets/49851476/fbe07fe0-8fe6-4607-a6fa-7a6540e0fcc7)

## Desired Outcome
Image should be showing like this in the profile page:
![image](https://github.com/WPUserManager/wp-user-manager/assets/49851476/9e88a3fe-fa46-4913-aefe-3e13990182b5)

Removing the srcset attribute was the workaround for it:
var avatares = document.getElementsByClassName("avatar-96");
var avatar = avatares[0];
avatar.removeAttribute("srcset");

## Steps to Reproduce

1. Enable the Custom Avatar option
2. Set an avatar from the account-edit page
3. See the error

## Related

- https://secure.helpscout.net/conversation/2265875030/4920/

## Acceptance Criteria

- [ ]

**Comment by wp-user-manager** [comment] 2023-07-13 06:55
@reygcalantaol could you take a look please?

**Comment by reygcalantaol** [comment] 2023-07-22 19:08
@MarkKevin08 
I can't reproduce the issue.

**Comment by MarkKevin08** [comment] 2023-07-24 08:03
Hello @reygcalantaol ,

Thanks for checking, could you please double-check the html through the console, and see if srcset exists for the avatar in the profile page from your end? Thanks in advance.

**Comment by reygcalantaol** [comment] 2023-08-20 09:00
@MarkKevin08 
Yes, the srcset exists. Please see the screenshot.
![image](https://github.com/WPUserManager/wp-user-manager/assets/1219402/5aa0b7a3-7e7e-4739-a3c8-834fa36aedc2)

**Comment by MarkKevin08** [comment] 2023-11-06 06:39
Hi @reygcalantaol , and @wp-user-manager  - I'm still able to recreate this issue:
https://share.zight.com/6quwbE0g

Theme used - WooCommerce Storefront, I also tried with Twenty-TwentryThree

**Comment by wp-user-manager** [comment] 2023-11-08 11:46
@reygcalantaol looks like you're uploading a webp image. @MarkKevin08 can you supply the exact image you're using so @reygcalantaol can test with it please

**Comment by MarkKevin08** [comment] 2023-11-09 06:19
Hi @reygcalantaol , here's a jpg image I tested it with as well - https://we.tl/t-VssMmtrO8y

**Comment by reygcalantaol** [comment] 2023-11-26 12:13
@MarkKevin08 
The image link is already expired. Can you send the image again?
Also, can you check if there are rules in the CSS at your that applies to SRCSET?
 
@wp-user-manager 
I tried again with jpg and it works fine.
I also tested with storefront and twenty-twenty-three theme.
![image](https://github.com/WPUserManager/wp-user-manager/assets/1219402/be1e3fa0-34e6-4ff4-b55d-f8b1e47e27e6)

**Comment by MarkKevin08** [comment] 2023-11-27 08:37
![test](https://github.com/WPUserManager/wp-user-manager/assets/49851476/05b1e5f8-627f-49c9-90bf-e1aa3ab5bda2)
Hi @reygcalantaol  - I tried reverting to a clean theme, but the issue persisted on my end:
https://share.zight.com/geu1e65n

This is even while using only WPUM on the site.

**Comment by reygcalantaol** [comment] 2024-03-16 13:12
@wp-user-manager  
Still not able to reproduce the issue.

@MarkKevin08
Have you tried testing in different browser? Based in your screenshot, the image is added in the DOM so I think the plugin is working with regards to rendering the image.

**Comment by wp-user-manager** [comment] 2024-03-16 13:41
Closing until we see again

**Closed by wp-user-manager** 2024-03-16 13:41 UTC
Labels: bug
